# Generated by Django 3.1.7 on 2021-04-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondershop', '0002_auto_20210403_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
