# Generated by Django 3.1.7 on 2021-04-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondershop', '0005_remove_shop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
