# Generated by Django 3.1.7 on 2021-04-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sondershop', '0006_shop_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='url',
        ),
    ]
