# Generated by Django 3.1.7 on 2021-04-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hack',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hack',
            name='file',
            field=models.FileField(blank=True, upload_to='hacken/files'),
        ),
        migrations.AlterField(
            model_name='hack',
            name='image',
            field=models.ImageField(blank=True, upload_to='hacken/images'),
        ),
    ]
