# Generated by Django 3.1.7 on 2021-04-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacken', '0002_auto_20210403_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hack',
            name='file',
            field=models.FileField(blank=True, upload_to='hacken/files/'),
        ),
        migrations.AlterField(
            model_name='hack',
            name='image',
            field=models.ImageField(blank=True, upload_to='hacken/images/'),
        ),
    ]
