# Generated by Django 3.1.7 on 2021-04-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacken', '0004_auto_20210404_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='hack',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
